server:
  port: 8900
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: 'jdbc:mysql://192.168.1.138:3306/warden_admin?allowMultiQueries=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8'
    username: 'user'
    password: 'user'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: 'GMT+8'
    date-format: 'yyyy-MM-dd HH:mm:ss'
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.microwarp.warden.stand.admin.handler.WardenEnumTypeHandler
warden:
  secure:
    aes-key: '4f6d817810d8ddca43d1241ea8a85134'
  global:
    result-model-package: true
    response-forever-ok: false
    enable-register: true